### ISSUE TITLE
Surface-Surface Contact Area Stats disappears

### ISSUE THREAD

**Issue by cathruff** [Ironhorse1618/Matlab-Imaris-XTensions#1]
The surface contact area stats disappears (no longer an option in the drop down menu) when I manipulate the surface image. This is most obvious when I try to change the color of the contact areas or the primary structure. Also when I use the statistic id feature to show the size of the contact area in a spectrum scale. It tends to rename the contact ares as Position X and then I no longer can find this variable.

**Comment by Ironhorse1618** [comment]
Thank you for the comment.  Part of this XTension creates a custom statistic in Imaris.  Although these custom statistics are saved as part of the IMS file itself, while in Imaris some actions in Imaris 9.6 and older, will cause custom stats created from ImarisXT to be deleted.   Imaris 9.6 is better than some of the earlier vesions, but it can still be a problem.  I suggest after running the script, save the resulting IMS file so that the stats can be restored if they get deleted.  some actions that may cause this is "adding new channels" and "recalculating or turning on new statistics" in Imaris.

**Comment by cathruff** [comment]
I see. Thank you very much.
